get_country_code<-function(country)
{
  if (country=="Andorra")  { 	code<-"AD"	
  } else if (country=="United Arab Emirates")	{ 	code<-"AE"
  } else if (country=="Afghanistan")	{ 	code<-"AF"
  } else if (country=="Antigua and Barbuda")	{ 	code<-"AG"
  } else if (country=="Anguilla")	{ 	code<-"AI"
  } else if (country=="Albania")	{ 	code<-"AL"
  } else if (country=="Armenia")	{ 	code<-"AM"
  } else if (country=="Angola")	{ 	code<-"AO"
  } else if (country=="Antarctica")	{ 	code<-"AQ"
  } else if (country=="Argentina")	{ 	code<-"AR"
  } else if (country=="American Samoa")	{ 	code<-"AS"
  } else if (country=="Austria")	{ 	code<-"AT"
  } else if (country=="Australia")	{ 	code<-"AU"
  } else if (country=="Aruba")	{ 	code<-"AW"
  } else if (country=="Åland Islands")	{ 	code<-"AX"
  } else if (country=="Azerbaijan")	{ 	code<-"AZ"
  } else if (country=="Bosnia and Herzegovina")	{ 	code<-"BA"
  } else if (country=="Barbados")	{ 	code<-"BB"
  } else if (country=="Bangladesh")	{ 	code<-"BD"
  } else if (country=="Belgium")	{ 	code<-"BE"
  } else if (country=="Burkina Faso")	{ 	code<-"BF"
  } else if (country=="Bulgaria")	{ 	code<-"BG"
  } else if (country=="Bahrain")	{ 	code<-"BH"
  } else if (country=="Burundi")	{ 	code<-"BI"
  } else if (country=="Benin")	{ 	code<-"BJ"
  } else if (country=="Saint Barthélemy")	{ 	code<-"BL"
  } else if (country=="Bermuda")	{ 	code<-"BM"
  } else if (country=="Brunei Darussalam")	{ 	code<-"BN"
  } else if (country=="Bolivia")  { 	code<-"BO"
  } else if (country=="Bolivia, Plurinational State of")	{ 	code<-"BO"
  } else if (country=="Bonaire, Sint Eustatius and Saba")	{ 	code<-"BQ"
  } else if (country=="Brazil")	{ 	code<-"BR"
  } else if (country=="Bahamas")	{ 	code<-"BS"
  } else if (country=="Bhutan")	{ 	code<-"BT"
  } else if (country=="Bouvet Island")	{ 	code<-"BV"
  } else if (country=="Botswana")	{ 	code<-"BW"
  } else if (country=="Belarus")	{ 	code<-"BY"
  } else if (country=="Belize")	{ 	code<-"BZ"
  } else if (country=="Canada")	{ 	code<-"CA"
  } else if (country=="Cocos (Keeling) Islands")	{ 	code<-"CC"
  } else if (country=="The Congo")  {   code<-"CD"
  } else if (country=="Congo")  { 	code<-"CD"
  } else if (country=="Congo, the Democratic Republic of the")  { 	code<-"CD"
  } else if (country=="The Democratic Republic of the Congo")	{ 	code<-"CD"
  } else if (country=="Central African Republic")	{ 	code<-"CF"
  } else if (country=="Congo")	{ 	code<-"CG"
  } else if (country=="Switzerland")	{ 	code<-"CH"
  } else if (country=="Côte d'Ivoire")	{ 	code<-"CI"
  } else if (country=="Cook Islands")	{ 	code<-"CK"
  } else if (country=="Chile")	{ 	code<-"CL"
  } else if (country=="Cameroon")	{ 	code<-"CM"
  } else if (country=="China")	{ 	code<-"CN"
  } else if (country=="Colombia")	{ 	code<-"CO"
  } else if (country=="Costa Rica")	{ 	code<-"CR"
  } else if (country=="Cuba")	{ 	code<-"CU"
  } else if (country=="Cabo Verde")	{ 	code<-"CV"
  } else if (country=="Curaçao")	{ 	code<-"CW"
  } else if (country=="Christmas Island")	{ 	code<-"CX"
  } else if (country=="Cyprus")	{ 	code<-"CY"
  } else if (country=="Czech Republic")	{ 	code<-"CZ"
  } else if (country=="Germany")	{ 	code<-"DE"
  } else if (country=="Djibouti")	{ 	code<-"DJ"
  } else if (country=="Denmark")	{ 	code<-"DK"
  } else if (country=="Dominica")	{ 	code<-"DM"
  } else if (country=="Dominican Republic")	{ 	code<-"DO"
  } else if (country=="Algeria")	{ 	code<-"DZ"
  } else if (country=="Ecuador")	{ 	code<-"EC"
  } else if (country=="Estonia")	{ 	code<-"EE"
  } else if (country=="Egypt")	{ 	code<-"EG"
  } else if (country=="Western Sahara")	{ 	code<-"EH"
  } else if (country=="Eritrea")	{ 	code<-"ER"
  } else if (country=="Spain")	{ 	code<-"ES"
  } else if (country=="Ethiopia")	{ 	code<-"ET"
  } else if (country=="Finland")	{ 	code<-"FI"
  } else if (country=="Fiji")	{ 	code<-"FJ"
  } else if (country=="Falkland Islands (Malvinas)")	{ 	code<-"FK"
  } else if (country=="Falkland Islands")  {   code<-"FK"
  } else if (country=="Malvinas")  { 	code<-"FK"
  } else if (country=="Micronesia, Federated States of")  { 	code<-"FM"
  } else if (country=="Micronesia")	{ 	code<-"FM"
  } else if (country=="Faroe Islands")	{ 	code<-"FO"
  } else if (country=="France")	{ 	code<-"FR"
  } else if (country=="Gabon")	{ 	code<-"GA"
  } else if (country=="United Kingdom of Great Britain and Northern Ireland")	{ 	code<-"GB"
  } else if (country=="United Kingdom")  {   code<-"GB"
  } else if (country=="Great Britain")  { 	code<-"GB"
  } else if (country=="Grenada")	{ 	code<-"GD"
  } else if (country=="Georgia")	{ 	code<-"GE"
  } else if (country=="French Guiana")	{ 	code<-"GF"
  } else if (country=="Guernsey")	{ 	code<-"GG"
  } else if (country=="Ghana")	{ 	code<-"GH"
  } else if (country=="Gibraltar")	{ 	code<-"GI"
  } else if (country=="Greenland")	{ 	code<-"GL"
  } else if (country=="Gambia")	{ 	code<-"GM"
  } else if (country=="Guinea")	{ 	code<-"GN"
  } else if (country=="Guadeloupe")	{ 	code<-"GP"
  } else if (country=="Equatorial Guinea")	{ 	code<-"GQ"
  } else if (country=="Greece")	{ 	code<-"GR"
  } else if (country=="South Georgia and the South Sandwich Islands")  { 	code<-"GS"
  } else if (country=="South Georgia")	{ 	code<-"GS"
  } else if (country=="Guatemala")	{ 	code<-"GT"
  } else if (country=="Guam")	{ 	code<-"GU"
  } else if (country=="Guinea-Bissau")	{ 	code<-"GW"
  } else if (country=="Guyana")	{ 	code<-"GY"
  } else if (country=="Hong Kong")	{ 	code<-"HK"
  } else if (country=="Heard Island and McDonald Islands")	{ 	code<-"HM"
  } else if (country=="Honduras")	{ 	code<-"HN"
  } else if (country=="Croatia")	{ 	code<-"HR"
  } else if (country=="Haiti")	{ 	code<-"HT"
  } else if (country=="Hungary")	{ 	code<-"HU"
  } else if (country=="Indonesia")	{ 	code<-"ID"
  } else if (country=="Ireland")	{ 	code<-"IE"
  } else if (country=="Israel")	{ 	code<-"IL"
  } else if (country=="Isle of Man")	{ 	code<-"IM"
  } else if (country=="India")	{ 	code<-"IN"
  } else if (country=="British Indian Ocean Territory")	{ 	code<-"IO"
  } else if (country=="Iraq")	{ 	code<-"IQ"
  } else if (country=="Iran, Islamic Republic of")  { 	code<-"IR"
  } else if (country=="Iran")	{ 	code<-"IR"
  } else if (country=="Iceland")	{ 	code<-"IS"
  } else if (country=="Italy")	{ 	code<-"IT"
  } else if (country=="Jersey")	{ 	code<-"JE"
  } else if (country=="Jamaica")	{ 	code<-"JM"
  } else if (country=="Jordan")	{ 	code<-"JO"
  } else if (country=="Japan")	{ 	code<-"JP"
  } else if (country=="Kenya")	{ 	code<-"KE"
  } else if (country=="Kyrgyzstan")	{ 	code<-"KG"
  } else if (country=="Cambodia")	{ 	code<-"KH"
  } else if (country=="Kiribati")	{ 	code<-"KI"
  } else if (country=="Comoros")	{ 	code<-"KM"
  } else if (country=="Saint Kitts and Nevis")	{ 	code<-"KN"
  } else if (country=="Korea, Democratic People's Republic of")  { 	code<-"KP"
  } else if (country=="Democratic People's Republic of Korea")	{ 	code<-"KP"
  } else if (country=="North Korea")  { 	code<-"KP"
  } else if (country=="South Korea")  { 	code<-"KR"
  } else if (country=="Republic of Korea")	{ 	code<-"KR"
  } else if (country=="Kuwait")	{ 	code<-"KW"
  } else if (country=="Cayman Islands")	{ 	code<-"KY"
  } else if (country=="Kazakhstan")	{ 	code<-"KZ"
  } else if (country=="Lao People's Democratic Republic")	{ 	code<-"LA"
  } else if (country=="Lebanon")	{ 	code<-"LB"
  } else if (country=="Saint Lucia")	{ 	code<-"LC"
  } else if (country=="Liechtenstein")	{ 	code<-"LI"
  } else if (country=="Sri Lanka")	{ 	code<-"LK"
  } else if (country=="Liberia")	{ 	code<-"LR"
  } else if (country=="Lesotho")	{ 	code<-"LS"
  } else if (country=="Lithuania")	{ 	code<-"LT"
  } else if (country=="Luxembourg")	{ 	code<-"LU"
  } else if (country=="Latvia")	{ 	code<-"LV"
  } else if (country=="Libya")	{ 	code<-"LY"
  } else if (country=="Morocco")	{ 	code<-"MA"
  } else if (country=="Monaco")	{ 	code<-"MC"
  } else if (country=="Moldova, Republic of")  { 	code<-"MD"
  } else if (country=="Republic of Moldova")  {   code<-"MD"
  } else if (country=="Moldova")	{ 	code<-"MD"
  } else if (country=="Montenegro")	{ 	code<-"ME"
  } else if (country=="Saint Martin (French part)")	{ 	code<-"MF"
  } else if (country=="Madagascar")	{ 	code<-"MG"
  } else if (country=="Marshall Islands")	{ 	code<-"MH"
  } else if (country=="Macedonia, the former Yugoslav Republic of")	{ 	code<-"MK"
  } else if (country=="Macedonia")	{ 	code<-"MK"
  } else if (country=="Mali")	{ 	code<-"ML"
  } else if (country=="Myanmar")	{ 	code<-"MM"
  } else if (country=="Mongolia")	{ 	code<-"MN"
  } else if (country=="Macao")	{ 	code<-"MO"
  } else if (country=="Northern Mariana Islands")	{ 	code<-"MP"
  } else if (country=="Martinique")	{ 	code<-"MQ"
  } else if (country=="Mauritania")	{ 	code<-"MR"
  } else if (country=="Montserrat")	{ 	code<-"MS"
  } else if (country=="Malta")	{ 	code<-"MT"
  } else if (country=="Mauritius")	{ 	code<-"MU"
  } else if (country=="Maldives")	{ 	code<-"MV"
  } else if (country=="Malawi")	{ 	code<-"MW"
  } else if (country=="Mexico")	{ 	code<-"MX"
  } else if (country=="Malaysia")	{ 	code<-"MY"
  } else if (country=="Mozambique")	{ 	code<-"MZ"
  } else if (country=="Namibia")	{ 	code<-"NA"
  } else if (country=="New Caledonia")	{ 	code<-"NC"
  } else if (country=="Niger")	{ 	code<-"NE"
  } else if (country=="Norfolk Island")	{ 	code<-"NF"
  } else if (country=="Nigeria")	{ 	code<-"NG"
  } else if (country=="Nicaragua")	{ 	code<-"NI"
  } else if (country=="Netherlands")	{ 	code<-"NL"
  } else if (country=="Norway")	{ 	code<-"NO"
  } else if (country=="Nepal")	{ 	code<-"NP"
  } else if (country=="Nauru")	{ 	code<-"NR"
  } else if (country=="Niue")	{ 	code<-"NU"
  } else if (country=="New Zealand")	{ 	code<-"NZ"
  } else if (country=="Oman")	{ 	code<-"OM"
  } else if (country=="Panama")	{ 	code<-"PA"
  } else if (country=="Peru")	{ 	code<-"PE"
  } else if (country=="French Polynesia")	{ 	code<-"PF"
  } else if (country=="Papua New Guinea")	{ 	code<-"PG"
  } else if (country=="Philippines")	{ 	code<-"PH"
  } else if (country=="Pakistan")	{ 	code<-"PK"
  } else if (country=="Poland")	{ 	code<-"PL"
  } else if (country=="Saint Pierre and Miquelon")	{ 	code<-"PM"
  } else if (country=="Pitcairn")	{ 	code<-"PN"
  } else if (country=="Puerto Rico")	{ 	code<-"PR"
  } else if (country=="Palestine, State of")	{ 	code<-"PS"
  } else if (country=="Portugal")	{ 	code<-"PT"
  } else if (country=="Palau")	{ 	code<-"PW"
  } else if (country=="Paraguay")	{ 	code<-"PY"
  } else if (country=="Qatar")	{ 	code<-"QA"
  } else if (country=="Réunion")	{ 	code<-"RE"
  } else if (country=="Romania")	{ 	code<-"RO"
  } else if (country=="Serbia")	{ 	code<-"RS"
  } else if (country=="Russia")  { 	code<-"RU"
  } else if (country=="Russian Federation")	{ 	code<-"RU"
  } else if (country=="Rwanda")	{ 	code<-"RW"
  } else if (country=="Saudi Arabia")	{ 	code<-"SA"
  } else if (country=="Solomon Islands")	{ 	code<-"SB"
  } else if (country=="Seychelles")	{ 	code<-"SC"
  } else if (country=="Sudan")	{ 	code<-"SD"
  } else if (country=="Sweden")	{ 	code<-"SE"
  } else if (country=="Singapore")	{ 	code<-"SG"
  } else if (country=="Saint Helena, Ascension and Tristan da Cunha")	{ 	code<-"SH"
  } else if (country=="Slovenia")	{ 	code<-"SI"
  } else if (country=="Svalbard and Jan Mayen")	{ 	code<-"SJ"
  } else if (country=="Slovakia")	{ 	code<-"SK"
  } else if (country=="Sierra Leone")	{ 	code<-"SL"
  } else if (country=="San Marino")	{ 	code<-"SM"
  } else if (country=="Senegal")	{ 	code<-"SN"
  } else if (country=="Somalia")	{ 	code<-"SO"
  } else if (country=="Suriname")	{ 	code<-"SR"
  } else if (country=="South Sudan")	{ 	code<-"SS"
  } else if (country=="Sao Tome and Principe")	{ 	code<-"ST"
  } else if (country=="U.S.S.R.")  { 	code<-"SU"
  } else if (country=="USSR")	{ 	code<-"SU"
  } else if (country=="El Salvador")	{ 	code<-"SV"
  } else if (country=="Sint Maarten (Dutch part)")	{ 	code<-"SX"
  } else if (country=="Syria")  { 	code<-"SY"
  } else if (country=="Syrian Arab Republic")	{ 	code<-"SY"
  } else if (country=="Swaziland")	{ 	code<-"SZ"
  } else if (country=="Turks and Caicos Islands")	{ 	code<-"TC"
  } else if (country=="Chad")	{ 	code<-"TD"
  } else if (country=="French Southern Territories")	{ 	code<-"TF"
  } else if (country=="Togo")	{ 	code<-"TG"
  } else if (country=="Thailand")	{ 	code<-"TH"
  } else if (country=="Tajikistan")	{ 	code<-"TJ"
  } else if (country=="Tokelau")	{ 	code<-"TK"
  } else if (country=="Timor-Leste")	{ 	code<-"TL"
  } else if (country=="Turkmenistan")	{ 	code<-"TM"
  } else if (country=="Tunisia")	{ 	code<-"TN"
  } else if (country=="Tonga")	{ 	code<-"TO"
  } else if (country=="Turkey")	{ 	code<-"TR"
  } else if (country=="Trinidad and Tobago")	{ 	code<-"TT"
  } else if (country=="Tuvalu")	{ 	code<-"TV"
  } else if (country=="Taiwan, Province of China")	{ 	code<-"TW"
  } else if (country=="Tanzania, United Republic of")	{ 	code<-"TZ"
  } else if (country=="Ukraine")	{ 	code<-"UA"
  } else if (country=="Uganda")	{ 	code<-"UG"
  } else if (country=="United States Minor Outlying Islands")	{ 	code<-"UM"
  } else if (country=="United States")	{ 	code<-"UM"
  } else if (country=="United States of America")	{ 	code<-"US"
  } else if (country=="Uruguay")	{ 	code<-"UY"
  } else if (country=="Uzbekistan")	{ 	code<-"UZ"
  } else if (country=="Holy See")	{ 	code<-"VA"
  } else if (country=="Saint Vincent and the Grenadines")	{ 	code<-"VC"
  } else if (country=="Venezuela")	{ 	code<-"VE"
  } else if (country=="Virgin Islands, British")	{ 	code<-"VG"
  } else if (country=="Virgin Islands, U.S.")	{ 	code<-"VI"
  } else if (country=="Viet Nam")	{ 	code<-"VN"
  } else if (country=="Vanuatu")	{ 	code<-"VU"
  } else if (country=="Wallis and Futuna")	{ 	code<-"WF"
  } else if (country=="Samoa")	{ 	code<-"WS"
  } else if (country=="Yemen")	{ 	code<-"YE"
  } else if (country=="Mayotte")	{ 	code<-"YT"
  } else if (country=="South Africa")	{ 	code<-"ZA"
  } else if (country=="Zambia")	{ 	code<-"ZM"
  } else if (country=="Zimbabwe")	{ 	code<-"ZW"
  }
  
  return (code)
}